-- Create account_transfers table and helper function for atomic transfers

create table if not exists public.account_transfers (
  id bigint generated by default as identity not null,
  sender_account_id uuid not null,
  receiver_account_id uuid not null,
  amount numeric not null,
  transfer_date date not null,
  notes text null,
  created_at timestamp with time zone not null default now(),
  constraint account_transfers_pkey primary key (id),
  constraint fk_receiver_account foreign key (receiver_account_id) references accounts (id) on delete restrict,
  constraint fk_sender_account foreign key (sender_account_id) references accounts (id) on delete restrict,
  constraint account_transfers_amount_check check ((amount > (0)::numeric)),
  constraint chk_different_accounts check ((sender_account_id <> receiver_account_id))
) tablespace pg_default;

create index if not exists idx_account_transfers_date on public.account_transfers using btree (transfer_date) tablespace pg_default;
create index if not exists idx_account_transfers_sender on public.account_transfers using btree (sender_account_id) tablespace pg_default;
create index if not exists idx_account_transfers_receiver on public.account_transfers using btree (receiver_account_id) tablespace pg_default;
